#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v25
# autospec commit: 9594167
#
Name     : routino
Version  : 3.4.3
Release  : 3
URL      : https://www.routino.org/download/routino-3.4.3.tgz
Source0  : https://www.routino.org/download/routino-3.4.3.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : AGPL-3.0-or-later
Requires: routino-bin = %{version}-%{release}
Requires: routino-data = %{version}-%{release}
Requires: routino-lib = %{version}-%{release}
BuildRequires : bzip2-dev
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: build-fixes.patch

%description
Routino : OpenStreetMap Routing Software
========================================

%package bin
Summary: bin components for the routino package.
Group: Binaries
Requires: routino-data = %{version}-%{release}

%description bin
bin components for the routino package.


%package data
Summary: data components for the routino package.
Group: Data

%description data
data components for the routino package.


%package dev
Summary: dev components for the routino package.
Group: Development
Requires: routino-lib = %{version}-%{release}
Requires: routino-bin = %{version}-%{release}
Requires: routino-data = %{version}-%{release}
Provides: routino-devel = %{version}-%{release}
Requires: routino = %{version}-%{release}

%description dev
dev components for the routino package.


%package doc
Summary: doc components for the routino package.
Group: Documentation

%description doc
doc components for the routino package.


%package lib
Summary: lib components for the routino package.
Group: Libraries
Requires: routino-data = %{version}-%{release}

%description lib
lib components for the routino package.


%prep
%setup -q -n routino-3.4.3
cd %{_builddir}/routino-3.4.3
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1745700015
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1745700015
rm -rf %{buildroot}
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/filedumper
/usr/bin/filedumper-slim
/usr/bin/filedumperx
/usr/bin/planetsplitter
/usr/bin/planetsplitter-slim
/usr/bin/router
/usr/bin/router+lib
/usr/bin/router+lib-slim
/usr/bin/router-slim

%files data
%defattr(-,root,root,-)
/usr/share/routino/profiles.xml
/usr/share/routino/tagging-drive.xml
/usr/share/routino/tagging-ride.xml
/usr/share/routino/tagging-walk.xml
/usr/share/routino/tagging.xml
/usr/share/routino/translations.xml

%files dev
%defattr(-,root,root,-)
/usr/include/routino.h
/usr/lib64/libroutino-slim.so
/usr/lib64/libroutino.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/routino/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libroutino-slim.so.0
/usr/lib64/libroutino-slim.so.0.0.0
/usr/lib64/libroutino.so.0
/usr/lib64/libroutino.so.0.0.0
